name: Test on Win
on: [push]
jobs:
  build:
    name: Box3 (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["windows-latest"]
        php-versions: ["7.2", "7.3", "7.4"]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, libsodium, mcrypt, gmp, sodium
          ini-values: post_max_size=256M, log_errors=1

      - name: Update composer
        run: composer self-update

      - name: Install Composer dependencies
        run: composer install

      - name: Smoke Test of composer
        run: composer --version

      - name: Compile Phar
        run: |
          mkdir bin
          php ./vendor/bin/box.bat compile

      - name: Run sample
        run: |
          dir .
          php D:\a\Practice_GitHub_Action-PHP_BOX3\Practice_GitHub_Action-PHP_BOX3\bin\sample
